_wandb:
    value:
        cli_version: 0.24.0
        e:
            edukug6caf50ijuxu26l3qohi5ovtfxk:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "10737418240"
                args:
                    - model.params.learning_rate=0.05
                    - model.params.max_depth=8
                    - model.params.n_estimators=50
                codePath: src/project99/train.py
                codePathLocal: src/project99/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "994662584320"
                        used: "590357323776"
                email: carldanielk@gmail.com
                executable: /opt/anaconda3/envs/project99/bin/python
                git:
                    commit: e184ac764b9d86bffeeb65c3dc6c61074bb49c4d
                    remote: https://github.com/lelegod/dtu_mlops_group99.git
                host: 00b98c0278.dynamic-ip4.rev.k-net.dk
                memory:
                    total: "17179869184"
                os: macOS-14.6.1-arm64-arm-64bit
                program: /Users/kyleelyk/Documents/DTU/SEM1/dtu_mlops_group99/src/project99/train.py
                python: CPython 3.12.12
                root: /Users/kyleelyk/Documents/DTU/SEM1/dtu_mlops_group99
                startedAt: "2026-01-23T04:08:52.683986Z"
                writerId: edukug6caf50ijuxu26l3qohi5ovtfxk
        m:
            - "1": validation_0-logloss
              "6":
                - 3
              "7":
                - 1
            - "1": validation_0-error
              "6":
                - 3
              "7":
                - 1
            - "1": validation_1-logloss
              "6":
                - 3
              "7":
                - 1
            - "1": validation_1-error
              "6":
                - 3
              "7":
                - 1
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 6
                - 50
                - 53
                - 105
            "2":
                - 1
                - 5
                - 6
                - 50
                - 53
                - 105
            "3":
                - 2
                - 7
                - 14
                - 16
                - 31
                - 63
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
        visualize:
            Feature Importance:
                panel_config:
                    fieldSettings:
                        label: Feature
                        value: Importance
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: Feature Importance
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Feature Importance_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
data:
    value:
        random_state: 42
        test_size: 0.2
learner:
    value:
        generic_param:
            device: cpu
            fail_on_invalid_gpu_id: "0"
            n_jobs: "0"
            nthread: "0"
            random_state: "0"
            seed: "0"
            seed_per_iteration: "0"
            validate_parameters: "1"
        gradient_booster:
            gbtree_model_param:
                num_parallel_tree: "1"
                num_trees: "0"
            gbtree_train_param:
                process_type: default
                tree_method: auto
                updater: grow_quantile_histmaker
                updater_seq: grow_quantile_histmaker
            name: gbtree
            specified_updater: false
            tree_train_param:
                alpha: "0"
                cache_opt: "1"
                colsample_bylevel: "1"
                colsample_bynode: "1"
                colsample_bytree: "1"
                eta: "0.0500000007"
                gamma: "0"
                grow_policy: depthwise
                interaction_constraints: ""
                lambda: "1"
                learning_rate: "0.0500000007"
                max_bin: "256"
                max_cat_threshold: "64"
                max_cat_to_onehot: "4"
                max_delta_step: "0"
                max_depth: "8"
                max_leaves: "0"
                min_child_weight: "1"
                min_split_loss: "0"
                monotone_constraints: ()
                refresh_leaf: "1"
                reg_alpha: "0"
                reg_lambda: "1"
                sampling_method: uniform
                sketch_ratio: "2"
                sparse_threshold: "0.20000000000000001"
                subsample: "1"
            updater:
                - hist_train_param:
                    debug_synchronize: "0"
                    extmem_single_page: "0"
                    max_cached_hist_node: "18446744073709551615"
                  name: grow_quantile_histmaker
        learner_model_param:
            base_score: '[5E-1]'
            boost_from_average: "1"
            num_class: "0"
            num_feature: "20"
            num_target: "1"
        learner_train_param:
            booster: gbtree
            disable_default_eval_metric: "0"
            multi_strategy: one_output_per_tree
            objective: binary:logistic
        metrics:
            - name: logloss
            - name: error
        objective:
            name: binary:logistic
            reg_loss_param:
                scale_pos_weight: "1"
model:
    value:
        eval_metric: '[''logloss'', ''error'']'
        learning_rate: 0.05
        max_depth: 8
        n_estimators: 50
        objective: binary:logistic
model.params.learning_rate:
    value: 0.05
model.params.max_depth:
    value: 8
model.params.n_estimators:
    value: 50
version:
    value:
        - 3
        - 1
        - 3
